### ISSUE TITLE
Typings for observer and getDerivedStateFromProps seem to be wrong

### ISSUE THREAD

**Issue by johnjesse** [mobxjs/mobx-react#515]
If I have a class with is decorated by `observer` and also uses `getDerivedStateFromProps` I get a typescript compilation error for the typings of the `nextProps` argument of  `getDerivedStateFromProps` -

`Type 'Readonly<any>' is not assignable to type 'IPropsInterface'.`

I cloned mobx-react to try it out, you can clearly see it if you edit compile-ts.tsx (I'm using vscode 1.24.1 and ts 2.9.2).

E.g. You see it for 
```
interface IPropsInterface {
	someState: any;
}

@observer
class T6 extends Component<IPropsInterface, {someState: any}> {

	static getDerivedStateFromProps(nextProps: IPropsInterface) {
		return {
			 someState: nextProps.someState
		 }
	}

	render() {
		return <span>
			<T3 hamburger={6} />
			{/* doesn't work with tsc 1.7.5: https://github.com/Microsoft/TypeScript/issues/5675 */}
			{/*<T4 sandwich={5} />*/}
			<T5 />
		</span>;
	}
}
```

**Comment by mweststrate** [comment]
Please create a sandbox or PR demonstrating the issue if this is still an issue

**Comment by johnjesse** [comment]
This is no longer an issue. I rolled back to fefc15f to make sure I hadn't screwed up initially. Not sure what has fixed it but it all works for me now with the latest version.
