### ISSUE TITLE
latest version of mobx and mobx-react isn't quite working with typescript

### ISSUE THREAD

**Issue by jonathanhotono** [mobxjs/mobx-react#635]
Running the latest version of mobx & mobx react in typescript 2.4.1 and React 16.3.2 seems to have some issue. I know the version of typescript seems old but I am using sharepoint framework to run this and kind of locked on this setting. Is there any recommended package version that works on both for mobx 4?

In my package.json:
`
"mobx": "~4.9.2",
"mobx-react": "~5.4.3"
`

Errors:
`
[22:30:36] Error - [tsc] node_modules/mobx-react/index.d.ts(44,13): error TS1005: ')' expected.
[22:30:36] Error - [tsc] node_modules/mobx-react/index.d.ts(44,43): error TS1005: ';' expected.
[22:30:36] Error - [tsc] node_modules/mobx-react/index.d.ts(44,46): error TS1109: Expression expected.
[22:30:36] Error - [tsc] node_modules/mobx-react/index.d.ts(44,69): error TS1005: '(' expected.
[22:30:36] Error - [tsc] node_modules/mobx-react/index.d.ts(45,1): error TS1005: ':' expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(10,69): error TS1005: '>'
expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(10,94): error TS1005: ';'
expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(10,98): error TS1109: Expression expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(10,103): error TS1005: ':' expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(10,125): error TS1005: ';' expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(10,130): error TS1109: Expression expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(10,141): error TS1005: ';' expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(10,145): error TS1005: ';' expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(10,166): error TS1005: '(' expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(10,178): error TS1005: ',' expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(10,182): error TS1109: Expression expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(11,74): error TS1005: ';'
expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(11,95): error TS1109: Expression expected.
[22:30:36] Error - [tsc] node_modules/mobx/lib/api/flow.d.ts(11,118): error TS1005: '(' expected.
[22:30:36] Error - 'tsc' sub task errored after 10 s
 exited with code 2
`

**Comment by CharlieIGG** [comment]
Based on previous issues I've had with Mobx + TS, I'm guessing the problem lies with the version of TS you have right now. I recommend you try upgrading to Typescript >= 2.6.1, <= 2.8.4

Let me know if that solves it for you @jonathanhotono

**Comment by jonathanhotono** [comment]
Yes thats the problem for me as I cant upgrade my typescript because I'm using sharepoint framework. I guess I'll try to find the best version that works with 2.4.1 for now until microsoft decides to upgrade spfx typescript version.

**Comment by mweststrate** [comment]
Use patch-package in your project, and override the .d.ts file with one
that use older syntax might be a solution with which you can stay at the
latest

Op za 26 jan. 2019 01:10 schreef Jonathan Aditya <notifications@github.com>:

**Comment by jonathanhotono** [comment]
@mweststrate thanks I'll try to consult with microsoft on this to update their typescript version on their next sharepoint framework version.
